services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=diarapp_db
      - POSTGRES_USER=diarapp_user
      - POSTGRES_PASSWORD=diarapp_password
    networks:
      - diarapp_network

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      - POSTGRES_DB=diarapp_db
      - POSTGRES_USER=diarapp_user
      - POSTGRES_PASSWORD=diarapp_password
      - POSTGRES_HOST=db
    depends_on:
      - db
    networks:
      - diarapp_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - diarapp_network

networks:
  diarapp_network:
    driver: bridge

volumes:
  postgres_data: