services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  web:
    build: .
    # NEW: Using Gunicorn for production traffic instead of runserver
    command: gunicorn --bind 0.0.0.0:8000 --chdir backend config.wsgi:application --workers 3
    volumes:
      - .:/app
      - media_data:/app/backend/media
      - static_data:/app/backend/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:1.31.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - media_data:/app/backend/media
      - static_data:/app/backend/static
    depends_on:
      - web

volumes:
  postgres_data:
  media_data:
  static_data: