# Generated by Django 5.0.3 on 2026-08-11 14:40

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PD', 'در انتظار'), ('IP', 'در حال انجام'), ('CP', 'تکمیل شده'), ('CC', 'لغو شده')], default='PD', max_length=2),
        ),
    ]
