# Generated by Django 5.0.3 on 2026-08-11 14:40

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('MT', 'مصالح'), ('WK', 'دستمزد کارگر'), ('TR', 'حمل و نقل'), ('EQ', 'تجهیزات'), ('FD', 'غذا'), ('FL', 'سوخت'), ('OT', 'سایر')], max_length=2),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
